---
title: Statistical Models
subtitle: Lecture Slides
author: 
  - name: Dr Silvio Fanzon
    affiliations: 
      - name: University of Hull
        department: Department of Mathematics
        state: United Kingdom
    email: S.Fanzon@hull.ac.uk
    url: https://www.silviofanzon.com
  - name: Dr John Fry
    affiliations: 
      - name: University of Hull
        department: Department of Mathematics
        state: United Kingdom
    email: J.M.Fry@hull.ac.uk
    url: https://www.hull.ac.uk/staff-directory/john-fry
date: 2024-01-15 
# To enter today's date replace by today
# Enter date formatted as dd MM yyyy
date-format: "D MMM YYYY"
---


# Welcome 



These are the Slides of the module **Statistical Models 551305** for T2 2023/24 at the University of Hull. 
If you have any question or find any typo, please email me at


::: {.content-visible when-format="html"}
<div style="text-align: center;">
**[S.Fanzon@hull.ac.uk](mailto: S.Fanzon@hull.ac.uk)**
</div>
:::


Up to date information about the module will be published on the University of Hull **Canvas Website**


::: {.content-visible when-format="html"}
<div style="text-align: center;">
**[canvas.hull.ac.uk/courses/70065](https://canvas.hull.ac.uk/courses/70065)**
</div>
:::


and on the **Course Webpage** hosted on my website


::: {.content-visible when-format="html"}
<div style="text-align: center;">
**[silviofanzon.com/blog/2023/Statistical-Models/](https://www.silviofanzon.com/blog/2023/Statistical-Models/)**
</div>
:::





# Slides


There are 11 lectures in this module. Topics and links to the slides can be found below.


| **Slides** | **Title** | 
|:------      |:------     |
| <a href="slides/lecture_1.qmd">Lecture 1</a>   | An introduction to Statistics     | 
| <a href="slides/lecture_2.qmd">Lecture 2</a>   | TBA     | 
: {tbl-colwidths="[20,80]"}





# Readings

**Main textbooks**:

- Statistics theory: The book by Bingham and Fry [@bingham-fry]
- Statistics in R: The book by Fry and Burke [@fry-burke]

**Reference books**:

- Probability & Statistics: The book by Casella and Berger [@casella-berger]
- Manual of R: The book by Dalgaard [@dalgaard]


