---
title: "Statistical Models"
subtitle: "Lecture 7"
from: markdown+emoji
author: 
    - name: Dr. Silvio Fanzon
      id: sf
      email: S.Fanzon@hull.ac.uk
      url: https://www.silviofanzon.com
      affiliations: University of Hull
    - name: Dr. John Fry
      id: jf
      email: J.M.Fry@hull.ac.uk
      url: https://www.hull.ac.uk/staff-directory/john-fry
      affiliations: University of Hull
---



::: {.content-hidden}
$
{{< include macros.tex >}}
$
:::




# Lecture 7: <br>The chi-squared test{background-color="#cc0164" visibility="uncounted"}

::: footer

<div color="#cc0164">  </div>

:::





## Outline of Lecture 7

1. Overview
2. The chi-squared goodness of fit test
3. The chi-squared test of independence/no association
4. Computational Example 1
5. Computational Example 2








# Part 1: <br>Overview {background-color="#cc0164" visibility="uncounted"}

::: footer

<div color="#cc0164">  </div>

:::




## Problem statement {.smaller}


**Data:** in the form of **numerical counts**

**Test:** difference between observed counts and predictions of theoretical model

**Example**: Blood counts

- Suppose to have counts of blood type for some people

    | A  |  B  |  AB  |  O  |
    |:--:|:---:|:----:|:---:|
    |2162| 738 | 228  |2876 |

- We want to compare the above to the probability model

    | A  |  B  |  AB  |  O  |
    |:--:|:---:|:----:|:---:|
    |1/3 | 1/8 |  1/24| 1/2 |
    




## Counts with multiple factors {.smaller}

**Example:** Relative performance of Man Utd managers

- Each football manager has Win, Draw and Loss count


| Manager | Played  |     Won |  Drawn  | Lost    |
|:-------:|:-------:|:-------:|:-------:|:-------:|
|  Moyes  |    51   |   27    | 9       |   15    |
|Van Gaal | 103     |   54    |  25     |   24    |
| Mourinho|  144    |   84    |  32     |   28    |
|Solskjaer|  168    |    91   |   37    |   40    |


**Questions:**

- Is the number of Wins, Draws and Losses uniformly distributed?
- Are there differences between the performances of each manager?



## Chi-squared test {.smaller}

- Hypothesis testing for counts can be done using chi-squared test

- Chi-squared test is simple to use for real-world project datasets (e.g. dissertations)

- Potentially applicable to a whole range of different models

- Easy to compute by hand/software

- Motivates the more advanced study of contingency tables




# Part 2: <br>Chi-squared <br> goodness of fit test {background-color="#cc0164" visibility="uncounted"}

::: footer

<div color="#cc0164">  </div>

:::




## Chi-squared goodness of fit test {.smaller}

**Categorical Data:** 

- Finite number of possible categories or types
- Observations can only belong to one category
- $O_i$ refers to observed count of category $i$

| Type $1$| Type $2$ |  $\ldots$ | Type $n$ |
|:-------:|:--------:|:---------:|:--------:|
|$O_1$    |   $O_2$  | $\ldots$  |    $O_n$ |

- $E_i$ refers to **expected count** of category $i$

| Type $1$| Type $2$ |  $\ldots$ | Type $n$ |
|:-------:|:--------:|:---------:|:--------:|
|$E_1$    |   $E_2$  | $\ldots$  |    $E_n$ |
 


## Chi-squared goodness of fit test {.smaller}

**Goal:** Compare expected counts $E_i$ with observed counts $O_i$

**Method:**

- Start with null hypothesis that theoretical model is correct
- Look for evidence against the null hypothesis
- Null hypothesis is wrong
    * if distance between observed counts and expected counts is large
    * For example if
    $$
    (O_i - E_i)^2 \geq c
    $$
    for some chosen constant $c$



## Chi-squared statistic {.smaller}

::: Definition

Global distance between observed and expected counts is defined as
$$
\chi^2 := \sum_{i=1}^n \frac{(O_i-E_i)^2}{E_i}
$$
The above is called **chi-squared statistic**

:::

**Note:** We have that 
$$
\chi^2 = 0 \qquad \iff \qquad O_i = E_i  \,\,\,\, \text{ for all } \,\,\,\, i = 1 , \, \ldots , \, n
$$


## Chi-squared statistic {.smaller}

**Remarks:**

- We expect small differences between $O_i$ and $E_i$ 
    * Therefore $\chi^2 > 0$

- However $O_i$ should not be too far away from $E_i$
    * Therefore $\chi^2$ should not be too large 

- The above imply that tests on $\chi^2$ should be one-sided





## Multinomial distribution {.smaller}

Multinomial distribution is a model for the following experiment: 
  
- The experiment consists of $m$ independent trials 
- Each trial results in one of $n$ distinct possible outcomes
- The probability of the $i$-th outcome is $p_i$ on every trial
- $X_i$ is the count of the number of times the $i$-th outcome occurred in the m trials
- For $n = 2$ this is a binomial experiment
    * Each trial has $n = 2$ possible outcomes
    * $X_1$ counts the number of *successes* 
    * $X_2 = m − X_1$ counts the number of *failures* in $m$ trials



## Multinomial distribution {.smaller}


::: Definition

Let $m,n \in \N$ and $p_1, \ldots, p_n$ numbers such that
$$
0 \leq p_i \leq 1 \,, \qquad \quad 
\sum_{i=1}^n p_i = 1
$$
The random vector $(X_1, \ldots, X_n)$ has **multinomial distribution** with $m$ trials and cell probabilities $p_1,\ldots,p_n$ if joint pmf if
$$
f (x_1, \ldots , x_n) = \frac{m!}{x_1 ! \cdot \ldots \cdot x_n !} \, p_1^{x_1} \cdot \ldots \cdot p_n^{x_n}
$$
whenever $x_1 + \ldots + x_n = m$. We denote $\XX \sim \multinomial(m,p_1,\ldots,p_n)$

:::



## Multinomial distribution {.smaller}
### Properties


Suppose that $\XX \sim \multinomial(m,p_1,\ldots,p_n)$

- Then $X_i$ is binomial with $m$ trials and probability $p_i$
- In this case we write $X_i \sim \binomial(m,p_i)$
- The pmf is
$$
f(x_i) = P(X = x_i) = \frac{m!}{x_i! \cdot (1-x_i)!} \, p_i^{x_i} (1-p_i)^{x_i}
$$
for all $x_i = 0 , \ldots , m$.
- We have
$$
\Expect[X_i] = m p_i \qquad \qquad 
\Var[X_i] = m p_i (1-p_i)
$$



## Theorem {.smaller}


- Chi-squared statistics is due to Karl Pearson in 1900 paper [link](https://www.tandfonline.com/doi/abs/10.1080/14786440009463897)

- Proof of Theorem is technical and incomprehensible on Pearson's paper

- Seven different proofs are presented in this paper [link](https://arxiv.org/abs/1808.09171)



this section and the next four sections, we shall consider statistical problems based on data such that each observation can be classified as belonging to one of a finite number of possible categories or types. Observations of this type are called categorical data. Since there are only a finite number of possible categories in these problems, and since we are int